In [4]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB() # clf is a classifier
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  0.96


In [5]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  0.9533333333333334


In [6]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  1.0


In [7]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  0.9933333333333333


In [8]:
# split data as 2/3 for training and 1/3 for testing
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # Test accuracy

Test Accuracy:  0.98


In [9]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.93333333 1.         1.         0.86666667 1.
 0.93333333 1.         1.         1.        ]
10CV Accuracy: 0.97 (+/- 0.09)


In [10]:
from sklearn.metrics import confusion_matrix
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [11]:
from sklearn.metrics import classification_report
target_names =['setosa', 'versicolor', 'virginica'] # provide class labels
print(classification_report(Y_test , Y_pred , target_names=target_names ))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.95      0.97        19
  virginica       0.94      1.00      0.97        15

avg / total       0.98      0.98      0.98        50



In [12]:
# 5 Lab exercise