In [1]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB() # clf is a classifier
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  0.96


In [2]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  0.9533333333333334


In [3]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  1.0


In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y , Y))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  0.9933333333333333


In [6]:
# split data as 2/3 for training and 1/3 for testing
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # Test accuracy

Test Accuracy:  0.98


In [7]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.93333333 1.         1.         0.86666667 1.
 0.93333333 1.         1.         1.        ]
10CV Accuracy: 0.97 (+/- 0.09)


In [8]:
from sklearn.metrics import confusion_matrix
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [22]:
print(Y_pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0 1 2 2 2 2]


In [9]:
from sklearn.metrics import classification_report
target_names =['setosa', 'versicolor', 'virginica'] # provide class labels
print(classification_report(Y_test , Y_pred , target_names=target_names ))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.95      0.97        19
  virginica       0.94      1.00      0.97        15

avg / total       0.98      0.98      0.98        50



In [10]:
# 5 Lab exercise

In [11]:
import pandas as pd
fileName = 'zooData.csv'
data = pd.read_csv(fileName)
#print(data)

data.drop(['animalName'], axis=1, inplace=True)
Y = data['type']
data.drop(['type'], axis=1, inplace=True)
X = data

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB() # clf is a classifier
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  1.0


In [12]:
from sklearn import tree
X = [[140, 1],[130, 1], [150, 0], [170, 0]]
Y = [1, 2, 3, 4]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [13]:
clf.predict([[170,1]])

array([1])

In [14]:
clf.predict_proba ([[170,1]])

array([[1., 0., 0., 0.]])

In [15]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris ()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data , iris.target)

In [16]:
import pydotplus
dot_data = tree.export_graphviz(clf, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("iris.pdf")

True

In [17]:
from IPython.display import Image
dot_data = tree.export_graphviz(clf,out_file=None,feature_names=iris.feature_names,class_names=iris.target_names ,filled=True , rounded=True ,special_characters=True)
graph = pydotplus.graph_from_dot_data (dot_data)
Image(graph.create_png())
graph.write_png("iris.png")

True

In [18]:
clf.predict(iris.data[:1, :])

array([0])

In [19]:
clf.predict_proba(iris.data[:1, :])

array([[1., 0., 0.]])

In [38]:
# binarization
import pandas
filename = 'breaset-cancer.csv'
data = pandas.read_csv(filename, encoding = "ISO-8859-1")
#print(data.shape) #make sure the whole data is being read
data = data.dropna()  # records with missing values are dropped here
#print(data.shape) # data without missing values
#print(data)
#data.INCOMEPERPERSON.iloc[0:] = -5000
#print (data)

import numpy as np
from sklearn.preprocessing import Binarizer
data.drop(['COUNTRY'], axis=1, inplace=True)
#datap = data.values
data.BREASTCANCERPER100TH.iloc[0:] [data.BREASTCANCERPER100TH.iloc[0:]<20 ] = 0
data.BREASTCANCERPER100TH.iloc[0:] [data.BREASTCANCERPER100TH.iloc[0:]>=20 ] = 1

#print(data)

In [68]:
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import neighbors , datasets
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

#problem 1
fileName = 'zooData.csv'
data = pd.read_csv(fileName)
print("* Problem 1 : Printing the zoo data set.... \n")
print(data)
data.drop(['animalName'], axis=1, inplace=True)
Y = data['type']
data.drop(['type'], axis=1, inplace=True)
X = data

#problem 2
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)
print("* Problem 2 :\n")
print("classification accuracy using decision tree classifier by training set... ")
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
print("\nclassification accuracy using decision tree classifier by splitting the data as 2/3 for training and 1/3 for testing... ")
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # Test accuracy

# 10-fold cross validation
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\nclassification accuracy using decision tree classifier by 10-fold cross validation... ")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

# 10 fold cross validation provides more realistic future performance as it uses the whole test set as trainning set and also as the test set in each fold
print("\nAnswer  : 10 fold cross validation provides more realistic future performance as it uses the whole test set as trainning set and also as the test set in each fold")

#problem 3

# it doesn't make any sense of having confusion matrix in trainning set where accuracy is 1.0 (diagonal matrix)
print("\n* Problem 3 :\n")
print("it doesn't make any sense of having confusion matrix in trainning set where accuracy is 1.0 (diagonal matrix)\n")

# by splitting the data as 2/3 for training and 1/3 for testing
clf = tree.DecisionTreeClassifier()
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using Decision tree classifier..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1)
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1)\n")

clf = GaussianNB()
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using GaussianNB..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1, 5 & 6) 
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1, 5 & 6)\n")

clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using MultinomialNB..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 5 classification errors have happend. (7 classified as 2 & 6, 1 classified as 5) 
print("in above confusion matrix 5 classification errors have happend. (7 classified as 2 & 6, 1 classified as 5) \n")

clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using KNeighbors Classifier..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) \n")

clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using SVM..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) \n")

print("\n* Problem 4 :\n")
clf = tree.DecisionTreeClassifier()
clf.fit(X,Y)
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("10-fold cross validation accuracy of Decision Tree Classifier\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf = GaussianNB()
clf.fit(X,Y)
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of GaussianNB\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of MultinomialNB\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of KNeighborsClassifier\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of SVM\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))


# Problem 5
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X,Y) # Model
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n* Problem 5 :")
print("\n\n10-fold cross validation accuracy of RandomForestClassifier\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using RandomForestClassifier..")
print(confusion_matrix(Y_test , Y_pred ))

* Problem 1 : Printing the zoo data set.... 

    animalName   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0     aardvark   True     False  False   True     False    False      True   
1     antelope   True     False  False   True     False    False     False   
2         bass  False     False   True  False     False     True      True   
3         bear   True     False  False   True     False    False      True   
4         boar   True     False  False   True     False    False      True   
5      buffalo   True     False  False   True     False    False     False   
6         calf   True     False  False   True     False    False     False   
7         carp  False     False   True  False     False     True     False   
8      catfish  False     False   True  False     False     True      True   
9         cavy   True     False  False   True     False    False     False   
10     cheetah   True     False  False   True     False    False      True   
11     chicken  Fa

E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few.



10-fold cross validation accuracy of GaussianNB

[1.    0.917 0.917 0.909 1.    0.889 0.889 1.    1.    1.   ]
10CV Accuracy: 0.95 (+/- 0.10)


10-fold cross validation accuracy of MultinomialNB

[0.923 0.917 0.833 0.909 0.9   0.889 0.889 0.778 1.    0.875]
10CV Accuracy: 0.89 (+/- 0.11)


10-fold cross validation accuracy of KNeighborsClassifier

[1.    0.917 1.    1.    0.9   1.    1.    1.    1.    1.   ]
10CV Accuracy: 0.98 (+/- 0.07)


10-fold cross validation accuracy of SVM

[1.    0.917 0.917 0.909 0.9   0.889 1.    1.    1.    1.   ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)




* Problem 5 :


10-fold cross validation accuracy of RandomForestClassifier

[1.    0.917 1.    1.    1.    0.889 1.    1.    1.    1.   ]
10CV Accuracy: 0.98 (+/- 0.08)

Confusion matrix using RandomForestClassifier..
[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 3  0  1  0  0  0  0]]
