In [1]:
# Problem 1

In [2]:
import pandas as pd
fileName = 'zooData.csv'
data = pd.read_csv(fileName)
print(data)

    animalName   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0     aardvark   True     False  False   True     False    False      True   
1     antelope   True     False  False   True     False    False     False   
2         bass  False     False   True  False     False     True      True   
3         bear   True     False  False   True     False    False      True   
4         boar   True     False  False   True     False    False      True   
5      buffalo   True     False  False   True     False    False     False   
6         calf   True     False  False   True     False    False     False   
7         carp  False     False   True  False     False     True     False   
8      catfish  False     False   True  False     False     True      True   
9         cavy   True     False  False   True     False    False     False   
10     cheetah   True     False  False   True     False    False      True   
11     chicken  False      True   True  False      True    False

In [3]:
data.drop(['animalName'], axis=1, inplace=True)
Y = data['type']
print(Y)

0            mammal
1            mammal
2              fish
3            mammal
4            mammal
5            mammal
6            mammal
7              fish
8              fish
9            mammal
10           mammal
11             bird
12             fish
13     invertebrate
14     invertebrate
15     invertebrate
16             bird
17           mammal
18             fish
19           mammal
20             bird
21             bird
22           mammal
23             bird
24           insect
25        amphibian
26        amphibian
27           mammal
28           mammal
29           mammal
           ...     
71             bird
72     invertebrate
73             fish
74           mammal
75           mammal
76          reptile
77     invertebrate
78             bird
79             bird
80          reptile
81     invertebrate
82             fish
83             bird
84           mammal
85     invertebrate
86             fish
87             bird
88           insect
89        amphibian


In [4]:
data.drop(['type'], axis=1, inplace=True)
X = data
print(X)

      hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
5     True     False  False   True     False    False     False     True   
6     True     False  False   True     False    False     False     True   
7    False     False   True  False     False     True     False     True   
8    False     False   True  False     False     True      True     True   
9     True     False  False   True     False    False     False     True   
10    True     False  False   True     False    False      True     True   
11   False      True   True  False      True    False     False    False   
12   False  

In [5]:
# Problem 2

In [6]:
# using training set
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  1.0


In [7]:
# by splitting the data as 2/3 for training and 1/3 for testing
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # Test accuracy

Test Accuracy:  0.9705882352941176


In [8]:
# 10-fold cross validation
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [9]:
# 10 fold cross validation provides more realistic future performance as it uses the whole test set as trainnig set and also as the test set in each fold

In [10]:
# Problem 3

In [11]:
# it doesn't make any sense of having confusion matrix in trainning set where accuracy is 1.0 (diagonal matrix)

In [12]:
# by splitting the data as 2/3 for training and 1/3 for testing
from sklearn.metrics import confusion_matrix
from sklearn import tree
clf = tree.DecisionTreeClassifier()
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 4  0  0  0  0  0  0]]


In [13]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1) 

In [14]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  0  0  2  1  0]]


In [15]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1, 5 & 6) 

In [16]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 0  0  0  0  1  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 0  0  3  0  0  1  0]]


In [17]:
# in above confusion matrix 5 classification errors have happend. (7 classified as 2 & 6, 1 classified as 5) 

In [18]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  3  0  0  0  0]]


In [19]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 

In [20]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  3  0  0  0  0]]


In [21]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 

In [22]:
# Problem 4

In [23]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X,Y)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [24]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 1.         0.88888889
 0.88888889 1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.10)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [25]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[0.92307692 0.91666667 0.83333333 0.90909091 0.9        0.88888889
 0.88888889 0.77777778 1.         0.875     ]
10CV Accuracy: 0.89 (+/- 0.11)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [26]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 1.         1.         0.9        1.
 1.         1.         1.         1.        ]
10CV Accuracy: 0.98 (+/- 0.07)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [27]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [28]:
# problem 5

In [29]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X,Y) # Model
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

E:\Program files\Anaconda\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


[1.         0.91666667 0.91666667 1.         0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.96 (+/- 0.09)
