In [1]:
# Problem 1

In [2]:
import pandas as pd
fileName = 'zooData.csv'
data = pd.read_csv(fileName)
print(data)

    animalName   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0     aardvark   True     False  False   True     False    False      True   
1     antelope   True     False  False   True     False    False     False   
2         bass  False     False   True  False     False     True      True   
3         bear   True     False  False   True     False    False      True   
4         boar   True     False  False   True     False    False      True   
5      buffalo   True     False  False   True     False    False     False   
6         calf   True     False  False   True     False    False     False   
7         carp  False     False   True  False     False     True     False   
8      catfish  False     False   True  False     False     True      True   
9         cavy   True     False  False   True     False    False     False   
10     cheetah   True     False  False   True     False    False      True   
11     chicken  False      True   True  False      True    False

In [3]:
data.drop(['animalName'], axis=1, inplace=True)
Y = data['type']
print(Y)

0            mammal
1            mammal
2              fish
3            mammal
4            mammal
5            mammal
6            mammal
7              fish
8              fish
9            mammal
10           mammal
11             bird
12             fish
13     invertebrate
14     invertebrate
15     invertebrate
16             bird
17           mammal
18             fish
19           mammal
20             bird
21             bird
22           mammal
23             bird
24           insect
25        amphibian
26        amphibian
27           mammal
28           mammal
29           mammal
           ...     
71             bird
72     invertebrate
73             fish
74           mammal
75           mammal
76          reptile
77     invertebrate
78             bird
79             bird
80          reptile
81     invertebrate
82             fish
83             bird
84           mammal
85     invertebrate
86             fish
87             bird
88           insect
89        amphibian


In [4]:
data.drop(['type'], axis=1, inplace=True)
X = data
print(X)

      hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
5     True     False  False   True     False    False     False     True   
6     True     False  False   True     False    False     False     True   
7    False     False   True  False     False     True     False     True   
8    False     False   True  False     False     True      True     True   
9     True     False  False   True     False    False     False     True   
10    True     False  False   True     False    False      True     True   
11   False      True   True  False      True    False     False    False   
12   False  

In [5]:
# Problem 2

In [6]:
# using training set
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

Training Accuracy:  1.0


In [7]:
# by splitting the data as 2/3 for training and 1/3 for testing
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # Test accuracy

Test Accuracy:  0.8823529411764706


In [8]:
# 10-fold cross validation
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [9]:
# 10 fold cross validation provides more realistic future performance as it uses the whole test set as trainnig set and also as the test set in each fold

In [10]:
# Problem 3

In [11]:
# it doesn't make any sense of having confusion matrix in trainning set where accuracy is 1.0 (diagonal matrix)

In [12]:
# by splitting the data as 2/3 for training and 1/3 for testing
from sklearn.metrics import confusion_matrix
from sklearn import tree
clf = tree.DecisionTreeClassifier()
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 4  0  0  0  0  0  0]]


In [13]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1) 

In [14]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  0  0  2  1  0]]


In [15]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1, 5 & 6) 

In [16]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 0  0  0  0  1  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 0  0  3  0  0  1  0]]


In [17]:
# in above confusion matrix 5 classification errors have happend. (7 classified as 2 & 6, 1 classified as 5) 

In [18]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  3  0  0  0  0]]


In [19]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 

In [20]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  3  0  0  0  0]]


In [21]:
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 

In [22]:
# Problem 4

In [23]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X,Y)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 0.8        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.94 (+/- 0.13)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [24]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 1.         0.88888889
 0.88888889 1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.10)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [25]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[0.92307692 0.91666667 0.83333333 0.90909091 0.9        0.88888889
 0.88888889 0.77777778 1.         0.875     ]
10CV Accuracy: 0.89 (+/- 0.11)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [26]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


[1.         0.91666667 1.         1.         0.9        1.
 1.         1.         1.         1.        ]
10CV Accuracy: 0.98 (+/- 0.07)


In [27]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.91666667 0.91666667 0.90909091 0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [28]:
# problem 5

In [29]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X,Y) # Model
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

E:\Program files\Anaconda\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


[1.         0.91666667 0.91666667 0.90909091 0.9        0.88888889
 1.         1.         1.         1.        ]
10CV Accuracy: 0.95 (+/- 0.09)


In [30]:
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 3  0  1  0  0  0  0]]


In [31]:
# Lab exercise II

In [32]:
# Problem 1

In [44]:
import pandas
filename = 'breaset-cancer.csv'
data = pandas.read_csv(filename, encoding = "ISO-8859-1")
print(data.shape) #make sure the whole data is being read
data = data.dropna()  # records with missing values are dropped here
print(data.shape) # data without missing values
print(data)

(289, 16)
(56, 16)
             COUNTRY  INCOMEPERPERSON  ALCCONSUMPTION  ARMEDFORCESRATE  \
5            Algeria      2231.993335            0.69         2.306817   
11         Argentina     10749.419238            9.35         0.560987   
14         Australia     25249.986061           10.21         0.486280   
15           Austria     26692.984107           12.40         0.815580   
16        Azerbaijan      2344.896916           13.34         1.976746   
19        Bangladesh       558.062877            0.17         0.287892   
21           Belarus      2737.670379           18.85         3.711930   
30            Brazil      4699.411262           10.08         0.721396   
33          Bulgaria      2549.558474           11.40         2.043388   
38            Canada     25575.352623           10.20         0.342976   
44             Chile      6334.105194            8.81         1.341114   
45             China      2425.471293            5.56         0.371357   
48          Colombi

In [57]:
import pandas
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

filename = 'breaset-cancer.csv'
data = pandas.read_csv(filename, encoding = "ISO-8859-1")
#print(data.shape) #make sure the whole data is being read
data = data.dropna()  # records with missing values are dropped here
#print(data.shape) # data without missing values
#print(data)

data.drop(['COUNTRY'], axis=1, inplace=True)

# BREASTCANCERPER100TH conversion
data.BREASTCANCERPER100TH.iloc[0:] [data.BREASTCANCERPER100TH.iloc[0:]<20 ] = 0
data.BREASTCANCERPER100TH.iloc[0:] [data.BREASTCANCERPER100TH.iloc[0:]>=20 ] = 1

# INCOMEPERPERSON conversion
data.INCOMEPERPERSON.iloc[0:] [data.INCOMEPERPERSON.iloc[0:]<2000 ] = 0
data.INCOMEPERPERSON.iloc[0:] [data.INCOMEPERPERSON.iloc[0:]>=2000 ] = 1

# ALCCONSUMPTION conversion
data.ALCCONSUMPTION.iloc[0:] [data.ALCCONSUMPTION.iloc[0:]<5 ] = 0
data.ALCCONSUMPTION.iloc[0:] [data.ALCCONSUMPTION.iloc[0:]>=5 ] = 1

# ARMEDFORCESRATE conversion
data.ARMEDFORCESRATE.iloc[0:] [data.ARMEDFORCESRATE.iloc[0:]<0.8 ] = 0
data.ARMEDFORCESRATE.iloc[0:] [data.ARMEDFORCESRATE.iloc[0:]>=0.8 ] = 1

# CO2EMISSIONS conversion
data.CO2EMISSIONS.iloc[0:] [data.CO2EMISSIONS.iloc[0:]<1.000000e+09 ] = 0
data.CO2EMISSIONS.iloc[0:] [data.CO2EMISSIONS.iloc[0:]>=1.000000e+09 ] = 1

# FEMALEEMPLOYRATE conversion
data.FEMALEEMPLOYRATE.iloc[0:] [data.FEMALEEMPLOYRATE.iloc[0:]<30 ] = 0
data.FEMALEEMPLOYRATE.iloc[0:] [data.FEMALEEMPLOYRATE.iloc[0:]>=30 ] = 1

# HIVRATE conversion
data.HIVRATE.iloc[0:] [data.HIVRATE.iloc[0:]<0.5 ] = 0
data.HIVRATE.iloc[0:] [data.HIVRATE.iloc[0:]>=0.5 ] = 1

# INTERNETUSERATE conversion
data.INTERNETUSERATE.iloc[0:] [data.INTERNETUSERATE.iloc[0:]<40 ] = 0
data.INTERNETUSERATE.iloc[0:] [data.INTERNETUSERATE.iloc[0:]>=40 ] = 1

# LIFEEXPECTANCY conversion
data.LIFEEXPECTANCY.iloc[0:] [data.LIFEEXPECTANCY.iloc[0:]<70 ] = 0
data.LIFEEXPECTANCY.iloc[0:] [data.LIFEEXPECTANCY.iloc[0:]>=70 ] = 1

# OILPERPERSON conversion
data.OILPERPERSON.iloc[0:] [data.OILPERPERSON.iloc[0:]<1 ] = 0
data.OILPERPERSON.iloc[0:] [data.OILPERPERSON.iloc[0:]>=1 ] = 1

# POLITYSCORE conversion
data.POLITYSCORE.iloc[0:] [data.POLITYSCORE.iloc[0:]<=0 ] = 0
data.POLITYSCORE.iloc[0:] [data.POLITYSCORE.iloc[0:]>0 ] = 1

# RELECTRICPERPERSON conversion
data.RELECTRICPERPERSON.iloc[0:] [data.RELECTRICPERPERSON.iloc[0:]<500 ] = 0
data.RELECTRICPERPERSON.iloc[0:] [data.RELECTRICPERPERSON.iloc[0:]>=500 ] = 1

# SUICIDEPER100TH conversion
data.SUICIDEPER100TH.iloc[0:] [data.SUICIDEPER100TH.iloc[0:]<7 ] = 0
data.SUICIDEPER100TH.iloc[0:] [data.SUICIDEPER100TH.iloc[0:]>=7 ] = 1

# EMPLOYRATE conversion
data.EMPLOYRATE.iloc[0:] [data.EMPLOYRATE.iloc[0:]<50 ] = 0
data.EMPLOYRATE.iloc[0:] [data.EMPLOYRATE.iloc[0:]>=50 ] = 1

# urbanrate conversion
data.urbanrate.iloc[0:] [data.urbanrate.iloc[0:]<50 ] = 0
data.urbanrate.iloc[0:] [data.urbanrate.iloc[0:]>=50 ] = 1

Y = data.BREASTCANCERPER100TH
data.drop(['BREASTCANCERPER100TH'], axis=1, inplace=True)
X = data

clf = tree.DecisionTreeClassifier()

X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print('Test Accuracy: ',accuracy_score(Y_test , Y_pred)) # Test accuracy


Test Accuracy:  1.0


In [58]:
# Lab01 full

In [60]:
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import neighbors , datasets
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

#problem 1
fileName = 'zooData.csv'
data = pd.read_csv(fileName)
print("* Problem 1 : Printing the zoo data set.... \n")
print(data)
data.drop(['animalName'], axis=1, inplace=True)
Y = data['type']
data.drop(['type'], axis=1, inplace=True)
X = data

#problem 2
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)
print("* Problem 2 :\n")
print("classification accuracy using decision tree classifier by training set... ")
print('Training Accuracy: ',clf.score(X,Y)) # Training accuracy

X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
print("\nclassification accuracy using decision tree classifier by splitting the data as 2/3 for training and 1/3 for testing... ")
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # Test accuracy

# 10-fold cross validation
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\nclassification accuracy using decision tree classifier by 10-fold cross validation... ")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

# 10 fold cross validation provides more realistic future performance as it uses the whole test set as trainning set and also as the test set in each fold
print("\nAnswer  : 10 fold cross validation provides more realistic future performance as it uses the whole test set as trainning set and also as the test set in each fold")

#problem 3

# it doesn't make any sense of having confusion matrix in trainning set where accuracy is 1.0 (diagonal matrix)
print("\n* Problem 3 :\n")
print("it doesn't make any sense of having confusion matrix in trainning set where accuracy is 1.0 (diagonal matrix)\n")

# by splitting the data as 2/3 for training and 1/3 for testing
clf = tree.DecisionTreeClassifier()
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using Decision tree classifier..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1)
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1)\n")

clf = GaussianNB()
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using GaussianNB..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1, 5 & 6) 
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1, 5 & 6)\n")

clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using MultinomialNB..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 5 classification errors have happend. (7 classified as 2 & 6, 1 classified as 5) 
print("in above confusion matrix 5 classification errors have happend. (7 classified as 2 & 6, 1 classified as 5) \n")

clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using KNeighbors Classifier..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) \n")

clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using SVM..")
print(confusion_matrix(Y_test , Y_pred ))
# in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) 
print("in above confusion matrix 4 classification errors have happend. (7 classified as 1 & 3) \n")

print("\n* Problem 4 :\n")
clf = tree.DecisionTreeClassifier()
clf.fit(X,Y)
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("10-fold cross validation accuracy of Decision Tree Classifier\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf = GaussianNB()
clf.fit(X,Y)
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of GaussianNB\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf=MultinomialNB() # clf is a classifier.
clf.fit(X,Y)
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of MultinomialNB\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1-Nearest Neighbor
clf.fit(X,Y) # Model
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of KNeighborsClassifier\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # clf is a classifier
clf.fit(X,Y) # Model
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n10-fold cross validation accuracy of SVM\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))


# Problem 5
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X,Y) # Model
scores = cross_val_score(clf, X, Y, cv=10) # 10-fold cross validation
print("\n\n* Problem 5 :")
print("\n\n10-fold cross validation accuracy of RandomForestClassifier\n")
print(scores) # Results for all the folds
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # clf is a classifier.
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print("\nConfusion matrix using RandomForestClassifier..")
print(confusion_matrix(Y_test , Y_pred ))

* Problem 1 : Printing the zoo data set.... 

    animalName   hair  feathers   eggs   milk  airborne  aquatic  predator  \
0     aardvark   True     False  False   True     False    False      True   
1     antelope   True     False  False   True     False    False     False   
2         bass  False     False   True  False     False     True      True   
3         bear   True     False  False   True     False    False      True   
4         boar   True     False  False   True     False    False      True   
5      buffalo   True     False  False   True     False    False     False   
6         calf   True     False  False   True     False    False     False   
7         carp  False     False   True  False     False     True     False   
8      catfish  False     False   True  False     False     True      True   
9         cavy   True     False  False   True     False    False     False   
10     cheetah   True     False  False   True     False    False      True   
11     chicken  Fa

E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few.



10-fold cross validation accuracy of GaussianNB

[1.    0.917 0.917 0.909 1.    0.889 0.889 1.    1.    1.   ]
10CV Accuracy: 0.95 (+/- 0.10)


10-fold cross validation accuracy of MultinomialNB

[0.923 0.917 0.833 0.909 0.9   0.889 0.889 0.778 1.    0.875]
10CV Accuracy: 0.89 (+/- 0.11)


10-fold cross validation accuracy of KNeighborsClassifier

[1.    0.917 1.    1.    0.9   1.    1.    1.    1.    1.   ]
10CV Accuracy: 0.98 (+/- 0.07)


10-fold cross validation accuracy of SVM

[1.    0.917 0.917 0.909 0.9   0.889 1.    1.    1.    1.   ]
10CV Accuracy: 0.95 (+/- 0.09)


E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
E:\Program files\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)




* Problem 5 :


10-fold cross validation accuracy of RandomForestClassifier

[1.    0.917 0.917 0.909 1.    0.889 1.    1.    1.    1.   ]
10CV Accuracy: 0.96 (+/- 0.09)

Confusion matrix using RandomForestClassifier..
[[ 1  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0 12  0]
 [ 3  0  1  0  0  0  0]]
